USE [master]
GO

/****** Object:  Database [CityDB]    Script Date: 01-07-2022 17:57:00 ******/
CREATE DATABASE [CityDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CityDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CityDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CityDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CityDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CityDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CityDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CityDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CityDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CityDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CityDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CityDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CityDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CityDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CityDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CityDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CityDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CityDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CityDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CityDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CityDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CityDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CityDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CityDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CityDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CityDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CityDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [CityDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CityDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CityDB] SET  MULTI_USER 
GO

ALTER DATABASE [CityDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CityDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CityDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CityDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CityDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CityDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CityDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CityDB] SET  READ_WRITE 
GO


